/* Original AUDADA life guide behaviours. MIT licensed. No network or analytics. */
'use strict';
(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bookmarkKey='audada-life-guide-saved-v1';
let saved=new Set();try{const v=JSON.parse(localStorage.getItem(bookmarkKey)||'[]');if(Array.isArray(v))saved=new Set(v.filter(x=>typeof x==='string'));}catch{}
const persistSaved=()=>{try{localStorage.setItem(bookmarkKey,JSON.stringify([...saved]));return true;}catch{return false;}};
const menu=$('#menu-toggle');if(menu)menu.addEventListener('click',()=>{const nav=$('#main-nav');const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
function drawSave(){ $$('[data-save]').forEach(b=>{const active=saved.has(b.dataset.save);b.setAttribute('aria-pressed',String(active));b.textContent=active?'已收藏':'收藏这篇';}); }
document.addEventListener('click',e=>{const b=e.target.closest('[data-save]');if(!b)return;const id=b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);const ok=persistSaved();drawSave();const status=$('#share-status');if(status)status.textContent=ok?'收藏只保存在当前浏览器。':'此浏览器不能长期保存，收藏仅在本次页面有效。';if($('#saved-only')?.checked)filter();});drawSave();
const copy=$('#copy-link');if(copy)copy.addEventListener('click',async()=>{const status=$('#share-status'),field=$('#share-field');if(location.protocol==='file:'){status.textContent='这是本地离线文件。网站上传后，再复制正式页面网址分享。';return;}const url=location.href;try{await navigator.clipboard.writeText(url);status.textContent='链接已复制，可以发给需要的人。';}catch{field.hidden=false;field.value=url;field.focus();field.select();status.textContent='请手动复制下方网址。';}});
$$('[data-print]').forEach(b=>b.addEventListener('click',()=>window.print()));
const checks=$$('[data-check]');if(checks.length){const key='audada-life-guide-checks-'+document.body.dataset.article;try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))checks.forEach(c=>c.checked=v.includes(c.dataset.check));}catch{}const update=()=>{$('#check-status').textContent='已核对 '+checks.filter(c=>c.checked).length+' / '+checks.length+' 项';};checks.forEach(c=>c.addEventListener('change',()=>{update();try{localStorage.setItem(key,JSON.stringify(checks.filter(c=>c.checked).map(c=>c.dataset.check)));}catch{$('#check-storage').textContent='本次页面可勾选；当前浏览器无法长期保存。';}}));$('#clear-checks')?.addEventListener('click',()=>{checks.forEach(c=>c.checked=false);try{localStorage.removeItem(key);}catch{}update();});update();}
const progress=$('#reading-progress');if(progress){const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?Math.min(100,Math.max(0,scrollY/max*100)):100)+'%';};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();}
const search=$('#guide-search'),resultBox=$('#results');let limit=24,matched=[];
const entries=window.AUDADA_INDEX||[];
const audience=$('#filter-audience'),category=$('#filter-category'),savedOnly=$('#saved-only');
function articleCard(a){return '<article class="result-card"><div class="result-meta">'+esc(a.category)+' · '+a.minutes+' 分钟阅读</div><h2><a href="articles/'+esc(a.slug)+'.html">'+esc(a.title)+'</a></h2><p>'+esc(a.summary)+'</p><div class="tags">'+a.audiences.map(x=>'<span class="tag">'+esc(x)+'</span>').join('')+'</div><div class="result-end"><span>'+esc(a.id)+'</span><button class="save-small" type="button" data-save="'+esc(a.id)+'" aria-pressed="'+saved.has(a.id)+'">'+(saved.has(a.id)?'已收藏':'收藏这篇')+'</button></div></article>';}
function render(){if(!resultBox)return;resultBox.innerHTML=matched.slice(0,limit).map(articleCard).join('');$('#result-count').textContent='找到 '+matched.length+' 篇专题 · 当前显示 '+Math.min(limit,matched.length)+' 篇';$('#no-results').hidden=matched.length!==0;$('#more-results').hidden=limit>=matched.length;drawSave();}
function filter(){if(!resultBox)return;const terms=(search?.value||'').toLowerCase().trim().split(/\s+/).filter(Boolean);matched=entries.map((a,i)=>({a,i})).filter(({a})=>(!audience.value||a.audiences.includes(audience.value))&&(!category.value||a.category===category.value)&&(!savedOnly.checked||saved.has(a.id))&&terms.every(t=>(a.id.toLowerCase()+" "+a.text).includes(t))).sort((x,y)=>{if(!terms.length)return x.i-y.i;const score=a=>terms.reduce((n,t)=>n+(a.title.toLowerCase().includes(t)?3:0)+(a.summary.toLowerCase().includes(t)?1:0),0);return score(y.a)-score(x.a)||x.i-y.i;}).map(x=>x.a);render();}
if(resultBox){const params=new URLSearchParams(location.search);search.value=params.get('q')||'';if([...audience.options].some(o=>o.value===params.get('audience')))audience.value=params.get('audience')||'';if([...category.options].some(o=>o.value===params.get('category')))category.value=params.get('category')||'';savedOnly.checked=params.get('saved')==='1';[search,audience,category,savedOnly].forEach(el=>el.addEventListener(el===search?'input':'change',()=>{limit=24;filter();}));$('#search-form')?.addEventListener('submit',e=>{e.preventDefault();limit=24;filter();$('#result-count').scrollIntoView({block:'center'});});$('#clear-filters').addEventListener('click',()=>{search.value='';audience.value='';category.value='';savedOnly.checked=false;limit=24;filter();});$('#more-results').addEventListener('click',()=>{limit+=24;render();});filter();}
$$('[data-query]').forEach(b=>b.addEventListener('click',()=>{const f=$('#home-search');if(f){f.value=b.dataset.query;$('#home-search-form').requestSubmit();}}));
const sourceSearch=$('#source-search');if(sourceSearch)sourceSearch.addEventListener('input',()=>{const q=sourceSearch.value.trim().toLowerCase();let n=0;$$('.source-card').forEach(el=>{el.hidden=!el.textContent.toLowerCase().includes(q);if(!el.hidden)n++;});$('#source-count').textContent='显示 '+n+' 个来源入口';});
const glossarySearch=$('#glossary-search');if(glossarySearch)glossarySearch.addEventListener('input',()=>{const q=glossarySearch.value.trim().toLowerCase();$$('[data-term-row]').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(q));});
const rent=$('#rent-amount');if(rent){const format=x=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:2}).format(x);const calc=()=>{const amount=Number(rent.value),period=$('#rent-period').value,extras=Number($('#other-costs').value);if(!Number.isFinite(amount)||amount<0||!Number.isFinite(extras)||extras<0){$('#rent-result').textContent='请填写不小于 0 的金额。';return;}const annual=amount*({week:52,fortnight:26,month:12}[period]);$('#rent-result').textContent='租金平均每月 '+format(annual/12)+'\n加上其他每月支出：'+format(annual/12+extras)+'\n全年租金：'+format(annual);};[rent,$('#rent-period'),$('#other-costs')].forEach(el=>el.addEventListener('input',calc));calc();}
const message=$('#message-kind');if(message){const templates={clarify:'Hello, I would like to confirm the requirements before I submit my application. Could you please send me the current document checklist, eligibility criteria and any fees in writing? Please also let me know the next step and the deadline. Thank you.',quote:'Hello, could you please provide an itemised written quote? Please include the total fee, any additional charges, what is included, the cancellation conditions and how long the quote is valid. I would like to understand the full cost before I agree.',followup:'Hello, I am following up on my enquiry submitted on [date], reference [reference]. Could you please confirm its current status, whether any information is missing, and the next step? I would appreciate a written response. Thank you.',interpreter:'Hello, I would like to request a Mandarin interpreter for my appointment. Could you please confirm whether you can arrange one, whether any fee applies, and what details you need from me?'};const update=()=>{$('#message-result').textContent=templates[message.value];};message.addEventListener('change',update);update();$('#copy-message').addEventListener('click',async()=>{const text=$('#message-result').textContent;try{await navigator.clipboard.writeText(text);$('#message-status').textContent='模板已复制。发送前替换括号内容，并核对事实。';}catch{$('#message-status').textContent='请手动选中上方模板复制。';}});}
})();
